/* Generated by critcl on Thu Nov 28 17:08:19 +0530 2024
 * source: D:/src/xtal/peg/xtal.dll
 * binary: D:/src/xtal/build/cache/v331_00000000000000000000000000000013_pic.obj
 */

#include "tclpre9compat.h" /* tcl.h + Portability Tcl <=8.6 */

/* ---------------------------------------------------------------------- */

#line 1 "MyInitTclStubs"

#if USE_TCL_STUBS
   const TclStubs *tclStubsPtr;
   const TclPlatStubs *tclPlatStubsPtr;
  const struct TclIntStubs *tclIntStubsPtr;
  const struct TclIntPlatStubs *tclIntPlatStubsPtr;

  static int
  MyInitTclStubs (Tcl_Interp *ip)
  {
    typedef struct {
      char *result;
      Tcl_FreeProc *freeProc;
      int errorLine;
      TclStubs *stubTable;
    } HeadOfInterp;

    HeadOfInterp *hoi = (HeadOfInterp*) ip;

    if (hoi->stubTable == NULL || hoi->stubTable->magic != TCL_STUB_MAGIC) {
      hoi->result = "This extension requires stubs-support.";
      hoi->freeProc = TCL_STATIC;
      return 0;
    }

    tclStubsPtr = hoi->stubTable;

    if (Tcl_PkgRequire(ip, "Tcl", TCL_VERSION, 0) == NULL) {
      tclStubsPtr = NULL;
      return 0;
    }

    if (tclStubsPtr->hooks != NULL) {
	tclPlatStubsPtr = tclStubsPtr->hooks->tclPlatStubs;
	tclIntStubsPtr = tclStubsPtr->hooks->tclIntStubs;
	tclIntPlatStubsPtr = tclStubsPtr->hooks->tclIntPlatStubs;
    }

    return 1;
  }
#endif

#ifdef __cplusplus
extern "C" {
#endif
      #line 1597 "critcl.tcl"
extern Tcl_AppInitProc ns_Xtal_Init;



DLLEXPORT int
Xtal_Init(Tcl_Interp *interp)
{
#define ip interp
#if USE_TCL_STUBS
  if (!MyInitTclStubs(interp)) return TCL_ERROR;
#endif

#line 1596 "critcl.tcl"
if (ns_Xtal_Init(interp) != TCL_OK) return TCL_ERROR;

 
  return TCL_OK;
#undef ip
}
#ifdef __cplusplus
}
#endif

